### ISSUE TITLE
Mongo Query issue for loginPasswordCriteria in EmployeeRepository

### ISSUE THREAD

**Issue by gauravghongde** [im-minion/ReferralPortalServices#4]
`Criteria loginPasswordCriteria = new Criteria("encryptedPassword").is(loginRequest.getPassword());`

> loginRequest.getPassword() will always be non encrypted and here compairing with encryptedPassword

**Comment by im-minion** [comment]
this code has not been used since we have the spring security in place.
I have checked in the new code removing these unused lines.
Thanks!
